# Generated by Django 2.1 on 2018-08-22 03:32

from django.db import migrations
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='goodtrack',
            field=user.models.ListField(blank=True),
        ),
    ]
