# Generated by Django 2.1 on 2018-08-28 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searchgoods', '0002_goodsdetail_goodshop'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goodsdetail',
            options={'ordering': ['-created_time']},
        ),
    ]
